package com.itstyle.model;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ORDER_NAME
     *
     * @mbggenerated
     */
    private String orderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.TOTAL_FEE
     *
     * @mbggenerated
     */
    private String totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.OUT_TRADE_NO
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.CREATE_DATE
     *
     * @mbggenerated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.UPDATE_DATE
     *
     * @mbggenerated
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ORDER_STATUS
     *
     * @mbggenerated
     * 0:已提交，1:已完成，2:已关闭
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.PAY_STATUS
     *
     * @mbggenerated
     * 0:未支付，1:已支付
     */
    private Integer payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.PRODUCT_ID
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ID
     *
     * @return the value of order_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ID
     *
     * @param id the value for order_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ORDER_NAME
     *
     * @return the value of order_info.ORDER_NAME
     *
     * @mbggenerated
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ORDER_NAME
     *
     * @param orderName the value for order_info.ORDER_NAME
     *
     * @mbggenerated
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName == null ? null : orderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.TOTAL_FEE
     *
     * @return the value of order_info.TOTAL_FEE
     *
     * @mbggenerated
     */
    public String getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.TOTAL_FEE
     *
     * @param totalFee the value for order_info.TOTAL_FEE
     *
     * @mbggenerated
     */
    public void setTotalFee(String totalFee) {
        this.totalFee = totalFee == null ? null : totalFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.OUT_TRADE_NO
     *
     * @return the value of order_info.OUT_TRADE_NO
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.OUT_TRADE_NO
     *
     * @param outTradeNo the value for order_info.OUT_TRADE_NO
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.CREATE_DATE
     *
     * @return the value of order_info.CREATE_DATE
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.CREATE_DATE
     *
     * @param createDate the value for order_info.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.UPDATE_DATE
     *
     * @return the value of order_info.UPDATE_DATE
     *
     * @mbggenerated
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.UPDATE_DATE
     *
     * @param updateDate the value for order_info.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ORDER_STATUS
     *
     * @return the value of order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ORDER_STATUS
     *
     * @param orderStatus the value for order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.PAY_STATUS
     *
     * @return the value of order_info.PAY_STATUS
     *
     * @mbggenerated
     */
    public Integer getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.PAY_STATUS
     *
     * @param payStatus the value for order_info.PAY_STATUS
     *
     * @mbggenerated
     */
    public void setPayStatus(Integer payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.USER_ID
     *
     * @return the value of order_info.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.USER_ID
     *
     * @param userId the value for order_info.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.PRODUCT_ID
     *
     * @return the value of order_info.PRODUCT_ID
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.PRODUCT_ID
     *
     * @param productId the value for order_info.PRODUCT_ID
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}